owner: ageg-status
repo: ageg-status.github.io
user-agent: mdaoustudes

skipTopicsUpdate: true

sites:
  - name: UdeS website (prod)
    url: https://www.usherbrooke.ca/
    icon: https://www.usherbrooke.ca/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 800

  - name: AGEG website (prod)
    url: https://www.ageg.ca/
    icon: https://www.ageg.ca/wp-content/uploads/2019/06/cropped-59079205_1502880046509656_7925612428161712128_n-192x192.png
    expectedStatusCodes:
      - 200
    maxResponseTime: 4000
  - name: AGEG website (redirect)
    url: https://ageg.ca/
    icon: https://www.ageg.ca/wp-content/uploads/2019/06/cropped-59079205_1502880046509656_7925612428161712128_n-192x192.png
    expectedStatusCodes:
      - 200
      - 301
    maxResponseTime: 4000

  - name: Vote (prod)
    url: https://vote.ageg.ca/
    icon: https://vote.ageg.ca/tmp/assets/c35a266c/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 800

  - name: Integrations (prod)
    url: https://integrations.ageg.ca/
    icon: https://integrations.ageg.ca/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 400
  - name: Integration (redirect)
    url: https://integration.ageg.ca/
    icon: https://integration.ageg.ca/favicon.ico
    expectedStatusCodes:
      - 200
      - 301
    maxResponseTime: 400
  - name: Integs (redirect)
    url: https://integs.ageg.ca/
    icon: https://integs.ageg.ca/favicon.ico
    expectedStatusCodes:
      - 200
      - 301
    maxResponseTime: 400
  - name: Integ (redirect)
    url: https://integ.ageg.ca/
    icon: https://integ.ageg.ca/favicon.ico
    expectedStatusCodes:
      - 200
      - 301
    maxResponseTime: 400

  - name: Okto (prod)
    url: https://okto.ageg.ca/
    icon: https://okto.ageg.ca/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 800
  - name: Oktoberfest (prod)
    url: https://oktoberfest.ageg.ca/
    icon: https://okto.ageg.ca/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 800
  - name: okto-ageg (gitlab page)
    url: https://okto-ageg.gitlab.io/
    expectedStatusCodes:
      - 200
    icon: https://about.gitlab.com/ico/favicon.ico
    maxResponseTime: 400
  - name: okto-ageg (staging)
    url: https://okto-ageg-staging.gitlab.io/
    icon: https://about.gitlab.com/ico/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 400

  - name: 2 Minutes de génie (prod)
    url: https://2mdg.ageg.ca/
    icon: https://2mdg.ageg.ca/images/logo-2mg.png
    expectedStatusCodes:
      - 200
    maxResponseTime: 400
  - name: 2 Minutes de génie (gitlab page)
    url: https://2mdg.gitlab.io/
    expectedStatusCodes:
      - 200
    icon: https://about.gitlab.com/ico/favicon.ico
    maxResponseTime: 400
  - name: 2 Minutes de génie (staging)
    url: https://2mdgstaging.gitlab.io/
    icon: https://about.gitlab.com/ico/favicon.ico
    expectedStatusCodes:
      - 200
    maxResponseTime: 400

  - name: Soutien à la vie étudiante (prod)
    url: https://www.usherbrooke.ca/etudiants/vie-etudiante/soutien-a-la-vie-etudiante
    expectedStatusCodes:
      - 200

  - name: Sécurité UdeS (prod)
    url: https://www.usherbrooke.ca/smsp/securite
    expectedStatusCodes:
      - 200
  - name: Sécurité UdeS (redirect)
    url: https://www.usherbrooke.ca/immeubles/la-securite/
    expectedStatusCodes:
      - 200
      - 303
  - name: Formulaire activités sécurité UdeS (prod)
    url: https://www.usherbrooke.ca/smsp/service-a-la-clientele/activites-sur-les-campus
    expectedStatusCodes:
      - 200
  - name: Formulaire activités sécurité UdeS (redirect)
    url: https://www.usherbrooke.ca/immeubles/la-securite/formulaires/
    expectedStatusCodes:
      - 200
      - 303

assignees:
  - mdaoustudes

status-website:
  cname: ageg-status.github.io
  logoUrl: https://www.ageg.ca/wp-content/uploads/2019/06/cropped-59079205_1502880046509656_7925612428161712128_n-1.png
  name: AGEG status
  introTitle: "Status page for AGEG related websites"
  theme: dark
  navbar:
    - title: UdeS status
      href: https://etatdesservices.usherbrooke.ca/

i18n:
  footer: This page is [open source]($REPO)

workflowSchedule:
  graphs: "0 0 * * *" #At 00:00.
  responseTime: "0 1-23/2 * * *" #At every 2 hours past 01:00.
  staticSite: "0 1 * * *" #At 01:00.
  summary: "0 0 * * *" #At 00:00.
  updateTemplate: "0 0 * * *" #At 00:00.
  updates: "0 3 * * *" #At 03:00.
  uptime: "*/10 * * * *" #At every 10th minute.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
